spring:
  ai:
    openai:
      api-key:
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat

    mcp:
      client:
        sse:
          connections:
            local:
              url: http://127.0.0.1:8081
        enabled: false


logging:
  level:
    org.springframework.ai.tool: debug