server:
  port: 8080

spring:
  application:
    name: email-coordinator

  # 邮件配置
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:your-email@gmail.com}
    password: ${EMAIL_PASSWORD:your-app-password}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  # Spring AI配置
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-openai-api-key}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
          max-tokens: 1000

# 日志配置
logging:
  level:
    io.eeaters.statemachine: DEBUG
    org.springframework.statemachine: DEBUG
    org.springframework.mail: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 邮件协调器配置
email-coordinator:
  # 轮询配置
  polling:
    enabled: true
    interval: 30000  # 30秒轮询一次
    max-attempts: 100 # 最大轮询次数
    initial-delay: 5000 # 初始延迟5秒

  # 邮件模板配置
  templates:
    initial-email:
      subject: "协调任务邀请"
      body: "您好，\n\n我们邀请您参与协调任务，请回复是否同意。\n\n谢谢！"

    follow-up-email:
      subject: "协调任务跟进"
      body: "您好，\n\n我们之前发送的协调任务邀请，希望您能回复确认。\n\n如果不同意，请告知具体原因。\n\n谢谢！"

  # 响应分析配置
  response-analysis:
    agree-keywords: ["同意", "确认", "好的", "OK", "yes", "accept", "确认参加"]
    disagree-keywords: ["不同意", "拒绝", "不能", "no", "reject", "无法参加"]

  # 任务配置
  task:
    timeout: 3600000 # 1小时超时 (毫秒)
    retry-count: 3 # 失败重试次数