spring:
  ai:
    openai:
      api-key: {api-key}
      chat:
        options:
          model: deepseek-chat
      base-url: https://api.deepseek.com

    vectorstore:
      qdrant:
        host: 175.24.164.112
        post: 6333